### ISSUE TITLE
t1-end is not working

### ISSUE THREAD

**Issue by bastianwegge** [apollographql/graphql-tutorial#13]
When I clone your repository and switch to t1-end I'm getting the following error after `npm install` or `yarn install`. I also completed your tutorial but in the end the code from the tutorial looks a little bit different than the branch.

I'd love to help and find what's wrong. Wrapping my head around this for 2 hours now.

```
Error in ./~/graphql-tools/dist/schemaGenerator.js
Module not found: 'graphql' in /Users/myuser/graphql-tutorial-helfer/client/node_modules/graphql-tools/dist

 @ ./~/graphql-tools/dist/schemaGenerator.js 18:16-34 20:16-34 21:16-34

Error in ./~/graphql-tools/dist/mock.js
Module not found: 'graphql' in /Users/myuser/graphql-tutorial-helfer/client/node_modules/graphql-tools/dist

 @ ./~/graphql-tools/dist/mock.js 3:16-34 4:16-34

Error in ./~/apollo-test-utils/dist/src/mocks/mockNetworkInterfaceWithSchema.js
Module not found: 'graphql' in /Users/myuser/graphql-tutorial-helfer/client/node_modules/apollo-test-utils/dist/src/mocks

 @ ./~/apollo-test-utils/dist/src/mocks/mockNetworkInterfaceWithSchema.js 3:16-34
```

**Comment by osfan501** [comment]
It might be a dependency issue with graphql. 

apollo-test-utils uses graphql@0.9.6
react-apollo uses graphql@0.10.1

**Comment by helfer** [comment]
Thanks @bastianwegge @osfan501 will fix shortly. Or one of you could make a PR! 😉

**Comment by osfan501** [comment]
I'm currently looking at https://github.com/sysgears/apollo-universal-starter-kit which seems to be working with similar dependencies and figuring out what's up.

**Comment by osfan501** [comment]
But I have to go to work and won't have computer access for the next 6 hours or so, but if it's not solved soon, I'll look at it more.

**Comment by helfer** [comment]
@bastianwegge @osfan501 I tried reproducing the issue, but I wasn't able to. A new clone and clean install of `t1-end` works just fine for me. I'm on mac, npm version 5 and node version 6 (but it also worked with npm 3 on node 5 just now).

Would you be able to provide a reproduction of this somehow? Thanks!

**Comment by helfer** [comment]
Ok, it seems the reason this worked for me is because I had `graphql` installed in a parent directory. After I removed it, I had to run `npm install --save graphql@^0.9.0`. Does that fix the problem for you @bastianwegge @osfan501 ?

**Comment by bastianwegge** [comment]
I'm giving this a shot right now. Couldn't get my other repository to work but I'm trying a clean install now.

**Comment by bastianwegge** [comment]
lol it's working for me now! Sorry for bothering you about it. Maybe some of the dependencies have changed since then. Thanks for the nice and direct feedback!

**Comment by helfer** [comment]
Yeah, I updated apollo-test-utils. I think that was the problem. I'm thinking about committing the npm5 lockfile to avoid problems like this in the future. 😃

**Comment by osfan501** [comment]
Lockfiles are awesome. Thanks for the clarification here.

On Jun 3, 2017 6:39 PM, "Jonas Helfer" <notifications@github.com> wrote:

Yeah, I updated apollo-test-utils. I think that was the problem. I'm
thinking about committing the npm5 lockfile to avoid problems like this in
the future. 😃

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/apollographql/graphql-tutorial/issues/13#issuecomment-306005636>,
or mute the thread
