### ISSUE TITLE
Module not found: 'graphql'

### ISSUE THREAD

**Issue by tetiogit** [apollographql/graphql-tutorial#3]
Should i import `graphql`? If I follow the tutorial I receive this error

```
Failed to compile.

Error in ./~/graphql-tools/dist/mock.js
Module not found: 'graphql' in /home/dp/swProjects/graphql-tutorial/client/node_modules/graphql-tools/dist

 @ ./~/graphql-tools/dist/mock.js 3:16-34 4:16-34

Error in ./~/graphql-tools/dist/schemaGenerator.js
Module not found: 'graphql' in /home/dp/swProjects/graphql-tutorial/client/node_modules/graphql-tools/dist

 @ ./~/graphql-tools/dist/schemaGenerator.js 18:16-34 20:16-34 21:16-34

Error in ./~/apollo-test-utils/dist/src/mocks/mockNetworkInterfaceWithSchema.js
Module not found: 'graphql' in /home/dp/swProjects/graphql-tutorial/client/node_modules/apollo-test-utils/dist/src/mocks

 @ ./~/apollo-test-utils/dist/src/mocks/mockNetworkInterfaceWithSchema.js 3:16-34
```

Same if I use the imports as per github `app.js`.

It doesn't happen instead if I use yarn... (yarn gives me only an unmet dependency of redux)

**Comment by 100ideas** [comment]
@tetiogit yes.

In the [tutorial](https://dev-blog.apollodata.com/full-stack-react-graphql-tutorial-582ac8d24e3b#443d) on medium.com, `graphql` is imported from `react-apollo` along with `ApolloClient`, `gql`, and `ApolloProvider`.

I used installed with `yarn add react-apollo` and yarn also installed the `graphql` package while complaining that it was an unmet peer dependency.

So you should probably add it to your package.json dependencies (`yarn add` or `npm install --save`). I'm not sure if npm would install graphql twice, once inside of the react-apollo node_modules, and again separately in the local node_modules root?
