### ISSUE TITLE
Network errors

### ISSUE THREAD

**Issue by ReggaePanda** [apollographql/graphql-tutorial#8]
<img width="893" alt="bildschirmfoto 2017-04-28 um 11 49 43" src="https://cloud.githubusercontent.com/assets/2183135/25523937/d4582ef0-2c08-11e7-898e-3779cce9824e.png">

this comes when I start t3-end 😟 

and when I change 
```js
const networkInterface = createNetworkInterface({ uri: 'http://localhost:4000/graphql' });
```
to
```js
const networkInterface = createNetworkInterface({
  uri: 'http://localhost:4000/graphql',
    opts: {
        mode: 'no-cors',
    }
 });
```

this error shows to console
<img width="879" alt="bildschirmfoto 2017-04-28 um 11 51 33" src="https://cloud.githubusercontent.com/assets/2183135/25524054/392186d8-2c09-11e7-9209-10f9c986914d.png">

 packages client
```
├── apollo-test-utils@0.1.2
├── false@0.0.4
├── graphql@0.9.4
├── graphql-tools@0.10.1
├── node-pre-gyp@0.6.34 extraneous
├── react@15.5.4
├── react-apollo@0.13.3
├── react-dom@15.5.4
└── react-scripts@0.9.3
```

packages server
```
├── babel-cli@6.24.1
├── babel-preset-es2015@6.24.1
├── babel-preset-stage-0@6.24.1
├── body-parser@1.17.1
├── express@4.15.2
├── graphql@0.9.4
├── graphql-server-express@0.6.0
├── graphql-tools@0.10.1
├── node-pre-gyp@0.6.34 extraneous
└── nodemon@1.11.0
```
EDIT:
<img width="629" alt="bildschirmfoto 2017-04-28 um 12 03 04" src="https://cloud.githubusercontent.com/assets/2183135/25524403/b84df04e-2c0a-11e7-8b96-b5435cf65187.png">
<img width="359" alt="bildschirmfoto 2017-04-28 um 12 03 24" src="https://cloud.githubusercontent.com/assets/2183135/25524407/bbe6bcd6-2c0a-11e7-8920-0edd97f9e4b3.png">

I think it's the plain text. but I don't not why

**Comment by helfer** [comment]
Thanks, I'll look into it!

**Comment by helfer** [comment]
Do you see the same error if you follow the tutorial?

**Comment by ReggaePanda** [comment]
no, the tutorial works fine. and now I found the missing lines in t3-end

server.js
```js
import cors from 'cors';
server.use('*', cors({ origin: 'http://localhost:3000' }));
```

**Comment by helfer** [comment]
Thanks, that's great! I think #9 will fix this 🙂
